### ISSUE TITLE
How to run webhook demo ?

### ISSUE THREAD

**Issue by lenhatvu** [chengxiaosheng/ZLMediaKit.HttpApi#3]
Hi,

can you tell me how to run webhook demo for ZLMediaServer ?

**Comment by chengxiaosheng** [comment]
1. You should configure ZLMediaKit->config.ini-> WebHook = 1.
2. You can configure the route of the listening by referring to  [Startup](https://github.com/chengxiaosheng/ZLMediaKit.HttpApi/blob/master/ZLMediaKit.WebHook.Demo/Startup.cs) .
`services.AddMediaKitWebHook(new APIRouteOptions(routePrefix : "app/api/zlhook"));`
3. The routing address configured in Step 2 should be consistent with ZLMediaKit's confi.ini.
```
[hook]
enable=1
on_flow_report=http[s]://your_host/app/api/zlhook/on_flow_report
on_play=http[s]://your_host/app/api/zlhook/on_play
on_publish=http[s]://your_host/app/api/zlhook/on_publish
more...
```

4. Refer to [HookService](https://github.com/chengxiaosheng/ZLMediaKit.HttpApi/blob/master/ZLMediaKit.WebHook.Demo/HookService.cs) To listen for Web Hook events.

**Comment by lenhatvu** [comment]
Thanks,

I will try
